dist: xenial
language: java
jdk:
 - openjdk12
cache:
 directories:
  - $HOME/.m2
script:
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
 - mvn -f releng/edu.toronto.cs.se.modelepedia.libz3java.releng/pom.xml clean install
 - mvn -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install
